export const portfolioData = [
    {
        title: "Warung Podomoro",
        description: "A restaurant ordering web application for an Indonesian-themed restaurant in South Korea. Ensure the smooth ordering process with a user-friendly interface and responsive design.",
        hashtags: ["Fullstack", "Responsive", "High Performance", "Real-time Data"],
        hue: 10,
        color: "#bc5856",
        icon: "/assets/images/favicon-podomoro.png",
        preview: "/assets/images/podomoro-ss.webp",
        link: "https://www.warung-podomoro.vercel.app",
        category: "Web Application",
    }, {
        title: "Rajawali Production Indonesia",
        description: "A profile website for a rigging and event equipment rental company. Designed by professional UI/UX designer.",
        hashtags: ["Responsive", "High Quality UI Design", "SEO Friendly", "Multilingual"],
        hue: 2,
        color: "#b9221d",
        icon: "/assets/images/favicon-rajawali.png",
        preview: "/assets/images/rajawali-ss.webp",
        link: "https://www.rajawaliproduction.com",
        category: "Company Profile",
    }, {
        title: "Es Coklat Duo Boedjang",
        description: "A website for a local ice chocolate beverage shop in Bogor. Features a fun and entertaining design to attract customers.",
        hashtags: ["Responsive", "Rich of Animation", "SEO Friendly"],
        hue: 15,
        color: "#3b170b",
        icon: "/assets/images/favicon-boedjang.png",
        preview: "/assets/images/boedjang-ss.webp",
        link: "https://escoklatduoboedjang.com/",
        category: "Company Profile",
    }, {      
        title: "Ahmad Naufal & Liska Feby",
        description: "My wedding invitation website. Features a simple and elegant design with an interactive message box.",
        hashtags: ["Interactive", "Elegant Design", "Mobile First"],
        hue: 2,
        color: "#964f57",
        icon: "/assets/images/favicon-wedding.png",
        preview: "/assets/images/wedding-ss.webp",
        link: "https://liskafeby.ahmadnaufal.dev/",
        category: "Wedding Invitation",
        dontUseBorderForPreview: true,
    }, {
        title: "Liska Feby Profile Website",
        description: "Profile website for my wife. Features an elegant yet attractive design with a touch of feminine color.",
        hashtags: ["Responsive", "Interactive", "SEO Friendly"],
        hue: 340,
        color: "#a95a63",
        icon: "/assets/images/favicon-ayang.png",
        preview: "/assets/images/ayang-ss.webp",
        link: "https://liska-feby.web.app",
        category: "Personal Portfolio",
    }];